env {
  job.mode = "BATCH"
  parallelism = 1
}

source {
  Jdbc {
    plugin_output = "src_PF临时出院数据26A"
    driver = "oracle.jdbc.OracleDriver"
    url = "jdbc:oracle:thin:@192.168.130.32:1521/xepdb1"
    user = "system"
    password = "123456"
    query = "SELECT 住院ID, 出院科室代码, 出院科室, 出院时间 FROM DL_PFM.\"PF临时出院数据26A\""
    connection_check_timeout_sec = 60
    fetch_size = 10000
    decimal_type_narrowing = false
  }
}

sink {
  Jdbc {
    plugin_input = "src_PF临时出院数据26A"
    driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    url = "jdbc:sqlserver://127.0.0.1:1433;databaseName=hospital_performance_dalian_derma;encrypt=false;trustServerCertificate=true"
    user = "sa"
    password = "YourStrongPassword123"
    database = "hospital_performance_dalian_derma"
    table = "PF临时出院数据26A"
    generate_sink_sql = true
    data_save_mode = "DROP_DATA"
    schema_save_mode = "ERROR_WHEN_SCHEMA_NOT_EXIST"
    connection_check_timeout_sec = 60
    batch_size = 10000
  }
}
